# Generated by Django 4.2.3 on 2024-09-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('slug_kat', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug_prdt', models.SlugField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upddated_at', models.DateTimeField(auto_now=True)),
                ('harga', models.IntegerField(default=0)),
                ('images', models.ImageField(blank=True, default='kosong.png', upload_to='')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olshopthrift.kategori')),
            ],
        ),
    ]
