# Generated by Django 4.2.3 on 2024-09-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshopthrift', '0002_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
    ]
