# Generated by Django 4.2.3 on 2025-01-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olshopthrift", "0003_product_is_hot"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(default="shopee.com"),
        ),
    ]
