# Generated by Django 4.2.3 on 2025-01-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olshopthrift", "0004_product_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="url",
            field=models.URLField(max_length=255),
        ),
    ]
